### ISSUE TITLE
Child logger caching

### ISSUE THREAD

**Issue by terrisgit** [good-ware/js-log#39]
logger() and child() currently return new objects and therefore callers should cache their return values. Here's a potential performance fix.

1. logger(cat, logger) will associate logger with the category cat and returns logger
2. Loggers::logger(cat) will associate the returned logger with the category cat but Logger::logger() does not do this
3. logger(foo) returns the logger associated with foo if it exists

Cache a child logger:
```
loggers.logger('a', loggers.child('t'))
```

**Comment by dev-guy** [comment]
v3.3.0
