### ISSUE TITLE
No-data console should optionally follow errors

### ISSUE THREAD

**Issue by terrisgit** [good-ware/js-log#43]
- A console transport created with data=false does not traverse error objects. This should be configurable.
- If the provided message is falsey and an error is provided in context, the error message should be logged

**Comment by dev-guy** [comment]
Try this.

loggers.info(undefined, {error: new Error('x')});

**Comment by dev-guy** [comment]
When the console transport is configured to not display data, it does not follow errors.  Justification: embedded errors are data. This should be configurable.

**Comment by dev-guy** [comment]
Fixed by #50
